from Config.colors import Colors
from Config.window import Window
from Logic.player import Player
from Logic.bullets import Bullets
from Logic.text import Text
from Logic.text import Score
from Logic.life import Life
from Logic.game import Game
from Client.client_socket import Client